create database UHBanco1
GO
USE UHBanco1
GO

create table usuario
(
   id int identity(100,5), 
   correo varchar(100), 
   clave varchar(50)
   CONSTRAINT PK_ID PRIMARY KEY(ID),
   CONSTRAINT UQ_CORREO UNIQUE(CORREO)

)

create TABLE EMPLEADOS (
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
SALARIO MONEY CONSTRAINT DF_SALARIO DEFAULT (500),
EDAD INT CONSTRAINT CHK_EDAD CHECK ( EDAD>=18 AND EDAD<=50)
)


CREATE TABLE BITACORA_EMPLEADOS (
ID INT ,
NOMBRE VARCHAR(100),
SALARIO MONEY ,
EDAD INT,
FECHA DATETIME,
USUARIO VARCHAR(30),
TRANSACCION VARCHAR(100)
)

--  INSERTED

--  DELETED

CREATE TRIGGER INSERTAR_EMPLEADOS
ON EMPLEADOS
AFTER INSERT

	  AS 
	  
	DECLARE @ID INT = (select id from inserted)
	DECLARE @NOMBRE VARCHAR(100) =(select NOMBRE from inserted)
	DECLARE @SALARIO MONEY =(select SALARIO from inserted)
	DECLARE @EDAD INT = (select edad from inserted)
	DECLARE @FECHA DATETIME = GETDATE();
	DECLARE @USUARIO VARCHAR(30) = 'dba'
	DECLARE @TRANSACCION VARCHAR(100) = 'INGRESO'
	    BEGIN
		INSERT INTO BITACORA_EMPLEADOS VALUES (@ID, @NOMBRE, @SALARIO,@EDAD,@FECHA,@USUARIO,@TRANSACCION)
		END


ALTER TRIGGER BORRADO_EMPLEADOS
ON EMPLEADOS
AFTER DELETE

	  AS 
	  
	DECLARE @ID INT = (select id from deleted)
	DECLARE @NOMBRE VARCHAR(100) =(select NOMBRE from deleted)
	DECLARE @SALARIO MONEY =(select SALARIO from deleted)
	DECLARE @EDAD INT = (select edad from deleted)
	DECLARE @FECHA DATETIME = GETDATE();
	DECLARE @USUARIO VARCHAR(30) = 'dba'
	DECLARE @TRANSACCION VARCHAR(100) = 'BORRADO'
	    BEGIN
		INSERT INTO BITACORA_EMPLEADOS VALUES (@ID, @NOMBRE, @SALARIO,@EDAD,@FECHA,@USUARIO,@TRANSACCION)
		END

EXEC REPORTE

CREATE TABLE PUESTO_EMPLEADO
(
  ID INT IDENTITY (1,1) ,
  ID_EMPLEADO INT,
  DESCRIPCION VARCHAR(100) NOT NULL
  CONSTRAINT PK_IDPUESTO PRIMARY KEY(ID)
  CONSTRAINT FK_IDEMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID)
)


INSERT INTO EMPLEADOS VALUES ('Esteban Ramirez',522,18)
delete from EMPLEADOS where id =5
select * from EMPLEADOS
select * from BITACORA_EMPLEADOS

delete  from PUESTO_EMPLEADO


INSERT INTO PUESTO_EMPLEADO (ID_EMPLEADO, DESCRIPCION) VALUES (1,'GERERENTE DE MERCADEO')


SELECT * FROM PUESTO_EMPLEADO
SELECT * FROM EMPLEADOS
SELECT * FROM BITACORA_EMPLEADOS



select * from empleados

